 int sfact[] = {
    gl.GL_ZERO, gl.GL_ONE, gl.GL_SRC_COLOR, gl.GL_ONE_MINUS_SRC_COLOR, gl.GL_DST_COLOR, 
    gl.GL_ONE_MINUS_DST_COLOR, gl.GL_SRC_ALPHA, gl.GL_ONE_MINUS_SRC_ALPHA, gl.GL_DST_ALPHA, 
    gl.GL_ONE_MINUS_DST_ALPHA, gl.GL_CONSTANT_COLOR, gl.GL_ONE_MINUS_CONSTANT_COLOR,
    gl.GL_CONSTANT_ALPHA, gl.GL_ONE_MINUS_CONSTANT_ALPHA, gl.GL_SRC_ALPHA_SATURATE  };
  int dfact[] = {
    gl.GL_ZERO, gl.GL_ONE, gl.GL_SRC_COLOR, gl.GL_ONE_MINUS_SRC_COLOR, gl.GL_DST_COLOR, 
    gl.GL_ONE_MINUS_DST_COLOR, gl.GL_SRC_ALPHA, gl.GL_ONE_MINUS_SRC_ALPHA, gl.GL_DST_ALPHA, 
    gl.GL_ONE_MINUS_DST_ALPHA, gl.GL_CONSTANT_COLOR, gl.GL_ONE_MINUS_CONSTANT_COLOR, 
    gl.GL_CONSTANT_ALPHA, gl.GL_ONE_MINUS_CONSTANT_ALPHA          };
